version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: emlyon_connect_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: emlyon
      POSTGRES_PASSWORD: emlyon2025
      POSTGRES_DB: emlyon_connect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U emlyon']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
